// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GroupBy1.Models
{
    [Table("Table_2")]
    public partial class DemoTable
    {
        public int Id { get; set; }
        public int? Number { get; set; }
        public int? Quantity1 { get; set; }
        public int? Mark2 { get; set; }
    }
}